### ISSUE TITLE
Not able to login into Plunker

### ISSUE THREAD

**Issue by jjayaraman** [filearts/plunker#104]
Since yesterday I am not able to login into Plunker.  https://plnkr.co/
Once I click sign in with git hub it opens git login but after entering the credentials it hangs.
I tried in other browsers like IE, Chrome, Safarai....all the same issue
Please fix

**Comment by iyip** [comment]
I experience the same issue

**Comment by vitalikpi** [comment]
The same for me. But I'm able to login on http://plnkr.co/

https version shows this error in console:

github:16 Uncaught SecurityError: Blocked a frame with origin "http://plnkr.co" from accessing a frame with origin "https://plnkr.co".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.

**Comment by bagusflyer** [comment]
Yes, got the same problem. Using http instead of https solve the problem.

**Comment by kwaazaar** [comment]
Yes! That fixed it!

The only browser where it still worked was Edge, but I prefer the Developer-tools of Chrome. So I'm VERY glad I found this!

**Comment by zainengineer** [comment]
It is still not working for me either

**Comment by shohan4556** [comment]
same problem

**Comment by shohan4556** [comment]
I am using chrome and still unable to login

**Comment by kwaazaar** [comment]
Read the comments guys: use http instead of https.

**Comment by RobbSadler** [comment]
still having trouble since the beginning - tried http and https, have cleared cookies, etc. On Chrome and Edge get a red "undefined" on the bottom right corner of the page. Even if this is a "nut that holds the key down" error, maybe the error message could be a bit more instructive. Would love to be using this with an actual login.

Thanks

**Comment by bojoer** [comment]
Same here used http & https from start and cleared cache and cache is enabled. All other Sign In using Github SSO sites are working. Other issue I notice is that when I am logged in, each time after pressing the button, I see the default gravatar Avatar logo while in console the correct Avatar URL,  https://avatars.githubusercontent.com/u/272220?v=3, is shown. Any more ideas?

**Comment by bojoer** [comment]
Additionally the following issue...

It seems to have solved itself. Refresh couple of times and logged in sometimes and logged out some other times. Also when pressing the logout button, then the Login button doesn’t work and after having logged out refresh page couple of times and automatically logged in again?

**Comment by RobbSadler** [comment]
Hoping against hope that possibly plnkr will do a bit more work on their auth since it has been over a year and I have never successfully logged in. I have tried from many different browsers and from different internet connections. IDK why I'm so special. I can log into GitHub (and everything else I use on the 'net). Don't understand why it's not possible on plnkr.

I have this in the console after a login attempt:
GET http://shot.plnkr.co/fIHGkf.png?d=2017-01-30T12:03:02.835Z 500 (Internal Server Error)
rkuCXg.png:1 
GET http://shot.plnkr.co/rkuCXg.png?d=2017-01-30T12:52:03.751Z 500 (Internal Server Error)
E13OwQ.png:1 
GET http://shot.plnkr.co/E13OwQ.png?d=2017-01-30T00:11:26.759Z 500 (Internal Server Error)
E824yr.png:1 
GET http://shot.plnkr.co/E824yr.png?d=2017-01-30T11:50:00.575Z 500 (Internal Server Error)
ESzSAz.png:1 
GET http://shot.plnkr.co/ESzSAz.png?d=2017-01-30T11:27:23.177Z 500 (Internal Server Error)
landing-0.11.6.js:formatted:8028AUTH Objectdocumentation_url: "https://developer.github.com/v3"message: "Bad credentials"service: "github"__proto__: Object
(anonymous) @ landing-0.11.6.js:formatted:8028
$eval @ landing-0.11.6.js:formatted:2828
$apply @ landing-0.11.6.js:formatted:2836
r @ landing-0.11.6.js:formatted:8027
(anonymous) @ landing-0.11.6.js:formatted:8040

Seems like this should be more straightforward. It would be nice to be able to save plnkrs, and reference them. If anyone's listening and needs more info, I'm happy to supply it.

I've ensured I am accessing via http, cleared the cache, cleared all cookies. Any input is appreciated.

**Comment by ggoodman** [comment]
Hi @RobbSadler, I'm plugging away at a rewrite. Core functionality is done. The new Auth will share nothing with the previous approach.

**Comment by RobbSadler** [comment]
You are that hero! Thanks!

**Comment by vivekamin** [comment]
Not able to Login :-1 same Problem. Undefined

**Comment by ethanzhoujie** [comment]
Yes, that works. use http instead of https

**Comment by ghost** [comment]
same problem, but I succeed to log in using http instead of https

**Comment by allenYdag-uman** [comment]
guys instead of this link 
https://plnkr.co/

remove the -s- from https and hit enter and try to log in again and its work 👍

**Comment by ggoodman** [comment]
This should be resolved as of today. Please let me know if you continue to experience issues.

**Comment by grmpfhmbl** [comment]
Sorry, still does not work. Go to https://plnkr.co sign in with GitHUB. Works and I'm signed in.
Reload page (CMD+R) and I'm signed out again.
Sign in again. Click on "Editor". Editor loads and I'm signed out again.

Using http instead of https as suggested by @allenYdag-uman does not make a difference and honestly - http is not an option for most internet users. Disabled all Ad-Blockers / Filter plugins, cleared cache, restarted browser just in case. No difference.

tested browsers:
- Chrome Version 58.0.3029.110 on MacOS X
- Safari Version 10.1.1 (10603.2.5)
- Firefox 53.0.3
